map_type: costmap
transform_tolerance: 0.2
obstacle_range: 4.9
raytrace_range: 5
inflation_radius: 0.5

observation_sources: base_scan

base_scan: {sensor_frame: base_laser_link,
            data_type: LaserScan,
            topic: base_scan,
            observation_persistence: 0.0,
            marking: true,
            clearing: true,
            min_obstacle_height: -0.10,
            max_obstacle_height: 2.0}

