# erratic-like
#footprint: [[0.133, 0.19],
#            [0.203, 0.115],
#            [0.203, -0.115],
#            [0.133, -0.19],
#            [-0.123, -0.19],
#            [-0.203, -0.103],
#            [-0.203, 0.103],
#            [-0.123, 0.19]]

#simplified
footprint: [[ 0.05,  0.05],
            [-0.05,  0.05],
            [-0.05, -0.05],
            [ 0.05, -0.05]]

controller_frequency: 20.0
controller_patience:  60.0
planner_patience:  60.0
clearing_radius: 0.1
footprint_padding: 0.01
#oscillation_timeout: 30.0
#oscillation_distance: 0.5


